/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROJECT21;

/**
 *
 * @author HP
 */
public class project21 extends javax.swing.JFrame {
    Double jam;
    Double gaji;        
    Double bonus;
    Double hasilakhir;

    /**
     * Creates new form project21
     */
    public project21() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fjam = new javax.swing.JTextField();
        ftarif = new javax.swing.JTextField();
        fbruto = new javax.swing.JTextField();
        fgaji = new javax.swing.JTextField();
        btnbruto = new javax.swing.JButton();
        btngaji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("hitung gaji karyawan");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        setForeground(new java.awt.Color(46, 46, 46));

        jPanel1.setBackground(new java.awt.Color(181, 255, 217));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(23, 0, 85));
        jLabel2.setText("MENGHITUNG GAJI KARYAWAN");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(23, 0, 85));
        jLabel3.setLabelFor(fjam);
        jLabel3.setText("Jumlah Jam Kerja :");

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(23, 0, 85));
        jLabel4.setLabelFor(ftarif);
        jLabel4.setText("Tarif Gaji Per-Jam :");

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(23, 0, 85));
        jLabel5.setLabelFor(fbruto);
        jLabel5.setText("Gaji Bruto :");

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(23, 0, 85));
        jLabel6.setLabelFor(fgaji);
        jLabel6.setText("Gaji Bersih :");

        fjam.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fjam.setForeground(new java.awt.Color(23, 0, 85));
        fjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fjamMouseClicked(evt);
            }
        });
        fjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fjamActionPerformed(evt);
            }
        });

        ftarif.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        ftarif.setForeground(new java.awt.Color(23, 0, 85));
        ftarif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftarifMouseClicked(evt);
            }
        });

        fbruto.setEditable(false);
        fbruto.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fbruto.setForeground(new java.awt.Color(23, 0, 85));
        fbruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fbrutoActionPerformed(evt);
            }
        });

        fgaji.setEditable(false);
        fgaji.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fgaji.setForeground(new java.awt.Color(23, 0, 85));

        btnbruto.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btnbruto.setForeground(new java.awt.Color(23, 0, 85));
        btnbruto.setText("Hitung Bruto");
        btnbruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrutoActionPerformed(evt);
            }
        });

        btngaji.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        btngaji.setForeground(new java.awt.Color(23, 0, 85));
        btngaji.setText("Hitung Gaji");
        btngaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngajiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fgaji, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftarif, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fjam, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fbruto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbruto)
                            .addComponent(btngaji)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnbruto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fbruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btngaji)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fgaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fjamMouseClicked
        // TODO add your handling code here:
//        if(fjam.getText().equals("Per Minggu")){
//            fjam.setForeground(new java.awt.Color(23, 0, 85));
//            fjam.setText("");
//        }
    }//GEN-LAST:event_fjamMouseClicked

    private void ftarifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftarifMouseClicked
        // TODO add your handling code here:
//        if(ftarif.getText().equals("Per Jam")){
//            ftarif.setForeground(new java.awt.Color(23, 0, 85));
//            ftarif.setText("");
//        }
    }//GEN-LAST:event_ftarifMouseClicked

    private void fjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fjamActionPerformed

    private void btnbrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrutoActionPerformed
        // TODO add your handling code here:
        hitungbruto();

    }//GEN-LAST:event_btnbrutoActionPerformed

    private void hitungbruto(){
        jam = Double.valueOf(fjam.getText());
        gaji = Double.parseDouble(ftarif.getText()); 
        bonus = gaji * 1.5;
        if(jam > 40){
            Double hasilgaji = gaji * 40;
            Double hasilbruto = bonus * (jam-40);
            hasilakhir = hasilgaji + hasilbruto;
            fbruto.setText(Double.toString(hasilakhir));
        }else if (jam <= 40) {
            hasilakhir = gaji * jam;
            fbruto.setText(Double.toString(hasilakhir));
        }
    }
    
    private void fbrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fbrutoActionPerformed
        // TODO add your handling code here:
        btnbrutoActionPerformed(evt);
    }//GEN-LAST:event_fbrutoActionPerformed

    private void btngajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngajiActionPerformed
        // TODO add your handling code here:
        Double potongan = hasilakhir * 0.1;
        Double bersih = hasilakhir - potongan;
        fgaji.setText(Double.toString(bersih));
    }//GEN-LAST:event_btngajiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project21.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project21().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbruto;
    private javax.swing.JButton btngaji;
    private javax.swing.JTextField fbruto;
    private javax.swing.JTextField fgaji;
    private javax.swing.JTextField fjam;
    private javax.swing.JTextField ftarif;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
