/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PROJECT22;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class project22 extends javax.swing.JFrame {
    Integer jmlh = 0;
    Integer ttl;

    /**
     * Creates new form project22
     */
    public project22() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fjumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnkurang = new javax.swing.JButton();
        btntambah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnpesan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fpesanan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ftotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        soto = new javax.swing.JRadioButton();
        rawon = new javax.swing.JRadioButton();
        lodeh = new javax.swing.JRadioButton();
        rendang = new javax.swing.JRadioButton();
        capcay = new javax.swing.JRadioButton();
        pecel = new javax.swing.JRadioButton();
        sate = new javax.swing.JRadioButton();
        mie = new javax.swing.JRadioButton();
        bakso = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(23, 0, 85));
        jPanel1.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setFont(new java.awt.Font("Edo SZ", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(181, 255, 217));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WARUNG TERSERAH");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(174, 0, 251));

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(181, 255, 217));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Jumlah Beli");

        fjumlah.setEditable(false);
        fjumlah.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        fjumlah.setForeground(new java.awt.Color(23, 0, 85));
        fjumlah.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fjumlah.setText("0");

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(181, 255, 217));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Informasi Pesanan");

        jPanel6.setBackground(new java.awt.Color(174, 0, 251));
        jPanel6.setLayout(new java.awt.GridLayout(3, 0, 5, 5));

        btnkurang.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        btnkurang.setForeground(new java.awt.Color(23, 0, 85));
        btnkurang.setText("-");
        btnkurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkurangActionPerformed(evt);
            }
        });

        btntambah.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        btntambah.setForeground(new java.awt.Color(23, 0, 85));
        btntambah.setText("+");
        btntambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahActionPerformed(evt);
            }
        });

        btnhapus.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(23, 0, 85));
        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnpesan.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        btnpesan.setForeground(new java.awt.Color(23, 0, 85));
        btnpesan.setText("Pesan");
        btnpesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(181, 255, 217));
        jLabel4.setText("Pesanan Anda :");

        fpesanan.setEditable(false);
        fpesanan.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fpesanan.setForeground(new java.awt.Color(23, 0, 85));

        jLabel5.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(181, 255, 217));
        jLabel5.setText("Harga Pesanan :");

        fharga.setEditable(false);
        fharga.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        fharga.setForeground(new java.awt.Color(23, 0, 85));

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(181, 255, 217));
        jLabel6.setText("Total Pesanan :");

        ftotal.setEditable(false);
        ftotal.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        ftotal.setForeground(new java.awt.Color(23, 0, 85));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnpesan))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fharga, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                            .addComponent(fpesanan))
                                        .addComponent(ftotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(fjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnkurang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntambah, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhapus)
                    .addComponent(btnpesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fpesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fharga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        jPanel3.setBackground(new java.awt.Color(181, 255, 217));
        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 10, 0));

        menu.add(soto);
        soto.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        soto.setForeground(new java.awt.Color(23, 0, 85));
        soto.setText("Soto Ayam");
        soto.setAlignmentY(0.0F);
        jPanel3.add(soto);

        menu.add(rawon);
        rawon.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        rawon.setForeground(new java.awt.Color(23, 0, 85));
        rawon.setText("Rawon");
        rawon.setAlignmentY(0.0F);
        jPanel3.add(rawon);

        menu.add(lodeh);
        lodeh.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        lodeh.setForeground(new java.awt.Color(23, 0, 85));
        lodeh.setText("Lodeh");
        lodeh.setAlignmentY(0.0F);
        jPanel3.add(lodeh);

        menu.add(rendang);
        rendang.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        rendang.setForeground(new java.awt.Color(23, 0, 85));
        rendang.setText("Rendang");
        rendang.setAlignmentY(0.0F);
        jPanel3.add(rendang);

        menu.add(capcay);
        capcay.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        capcay.setForeground(new java.awt.Color(23, 0, 85));
        capcay.setText("Capcay");
        capcay.setAlignmentY(0.0F);
        jPanel3.add(capcay);

        menu.add(pecel);
        pecel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        pecel.setForeground(new java.awt.Color(23, 0, 85));
        pecel.setText("Pecel");
        pecel.setAlignmentY(0.0F);
        jPanel3.add(pecel);

        menu.add(sate);
        sate.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        sate.setForeground(new java.awt.Color(23, 0, 85));
        sate.setText("Sate Ayam");
        sate.setAlignmentY(0.0F);
        jPanel3.add(sate);

        menu.add(mie);
        mie.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        mie.setForeground(new java.awt.Color(23, 0, 85));
        mie.setText("Mie Ayam");
        mie.setAlignmentY(0.0F);
        jPanel3.add(mie);

        menu.add(bakso);
        bakso.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        bakso.setForeground(new java.awt.Color(23, 0, 85));
        bakso.setText("Bakso");
        bakso.setAlignmentY(0.0F);
        jPanel3.add(bakso);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(181, 255, 217));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Selamat Menikmati Pesanan");
        jPanel1.add(jLabel7, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesanActionPerformed
        // TODO add your handling code here:
        if (jmlh > 0){
            if (soto.isSelected()){
                fpesanan.setText("Soto Ayam");
                fharga.setText("Rp. 10.000");
                ttl = jmlh * 10000;
                ftotal.setText(Integer.toString(ttl));
            }else if (rawon.isSelected()){
                fpesanan.setText("Rawon");
                fharga.setText("Rp. 13.000");
                ttl = jmlh * 13000;
                ftotal.setText(Integer.toString(ttl));
            }else if (lodeh.isSelected()){
                fpesanan.setText("Lodeh");
                fharga.setText("Rp. 15.000");
                ttl = jmlh * 15000;
                ftotal.setText(Integer.toString(ttl));
            }else if (rendang.isSelected()){
                fpesanan.setText("Rendang");
                fharga.setText("Rp. 17.000");
                ttl = jmlh * 17000;
                ftotal.setText(Integer.toString(ttl));
            }else if (capcay.isSelected()){
                fpesanan.setText("Capcay");
                fharga.setText("Rp. 11.000");
                ttl = jmlh * 11000;
                ftotal.setText(Integer.toString(ttl));
            }else if (pecel.isSelected()){
                fpesanan.setText("Pecel");
                fharga.setText("Rp. 9.000");
                ttl = jmlh * 9000;
                ftotal.setText(Integer.toString(ttl));
            }else if (sate.isSelected()){
                fpesanan.setText("Sate Ayam");
                fharga.setText("Rp. 18.000");
                ttl = jmlh * 18000;
                ftotal.setText(Integer.toString(ttl));
            }else if (mie.isSelected()){
                fpesanan.setText("Mie Ayam");
                fharga.setText("Rp. 8.000");
                ttl = jmlh * 8000;
                ftotal.setText(Integer.toString(ttl));
            }else if (bakso.isSelected()){
                fpesanan.setText("Bakso");
                fharga.setText("Rp. 10.000");
                ttl = jmlh * 10000;
                ftotal.setText(Integer.toString(ttl));
            }
        }else if (jmlh == 0){
            JOptionPane.showMessageDialog(null, "Masukkan Jumlah Pesanan!");
        }
        
    }//GEN-LAST:event_btnpesanActionPerformed

    private void btntambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahActionPerformed
        // TODO add your handling code here:
        jmlh = Integer.parseInt(fjumlah.getText());
        if(jmlh >= 0){
            jmlh = jmlh + 1;
            fjumlah.setText(Integer.toString(jmlh));
        }
    }//GEN-LAST:event_btntambahActionPerformed

    private void btnkurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkurangActionPerformed
        // TODO add your handling code here:
        jmlh = Integer.parseInt(fjumlah.getText());
        if(jmlh > 0){
            jmlh = jmlh - 1;
            fjumlah.setText(Integer.toString(jmlh));
        }
    }//GEN-LAST:event_btnkurangActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        fpesanan.setText("");
        fharga.setText("");
        ftotal.setText("");
        menu.clearSelection();
        fjumlah.setText("0");
    }//GEN-LAST:event_btnhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project22.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project22().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bakso;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnkurang;
    private javax.swing.JButton btnpesan;
    private javax.swing.JButton btntambah;
    private javax.swing.JRadioButton capcay;
    private javax.swing.JTextField fharga;
    private javax.swing.JTextField fjumlah;
    private javax.swing.JTextField fpesanan;
    private javax.swing.JTextField ftotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton lodeh;
    private javax.swing.ButtonGroup menu;
    private javax.swing.JRadioButton mie;
    private javax.swing.JRadioButton pecel;
    private javax.swing.JRadioButton rawon;
    private javax.swing.JRadioButton rendang;
    private javax.swing.JRadioButton sate;
    private javax.swing.JRadioButton soto;
    // End of variables declaration//GEN-END:variables
}
